import de.bluecolored.bluemap.core.util.math.MatrixM4f;

import java.util.StringJoiner;

// Emits crates/bm-resources/src/blockstate/ref_data.rs. Compile like MathRef (run.sh), then:
// java -cp <out> BlockstateRef > crates/bm-resources/src/blockstate/ref_data.rs
public class BlockstateRef {

    // verbatim from VariantSet.hashToFloat (private there)
    static float hashToFloat(int x, int y, int z) {
        final long hash = x * 73438747L ^ y * 9357269L ^ z * 4335792L;
        return (hash * (hash + 456149) & 0x00ffffff) / (float) 0x01000000;
    }

    // VariantSet.forEach(x, y, z, consumer) with the weights summed as in summarizeWeights
    static int pick(double[] weights, int x, int y, int z) {
        double total = 0;
        for (double w : weights) total += w;
        double selection = hashToFloat(x, y, z) * total;
        for (int i = 0; i < weights.length; i++) {
            selection -= weights[i];
            if (selection <= 0) return i;
        }
        return -1;
    }

    static String f(float v) { return String.format("0x%08x", Float.floatToRawIntBits(v)); }

    public static void main(String[] args) {
        StringBuilder s = new StringBuilder("// @generated by tools/javaref/BlockstateRef.java (BlueMap VariantSet/Variant + MatrixM4f, JDK 25). Do not edit.\n\n");

        int[][] pos = new int[64][];
        int[][] fixed = {{0, 0, 0}, {1, 2, 3}, {-1, -64, -1}, {Integer.MAX_VALUE, 319, Integer.MIN_VALUE}, {30000000, 100, -30000000}, {-29999999, -2048, 29999999}};
        System.arraycopy(fixed, 0, pos, 0, fixed.length);
        long seed = 0x5DEECE66DL;
        for (int i = fixed.length; i < pos.length; i++) {
            int[] p = new int[3];
            for (int j = 0; j < 3; j++) {
                seed = seed * 6364136223846793005L + 1442695040888963407L;
                p[j] = (int) (seed >>> 32);
            }
            pos[i] = p;
        }

        double[][] weights = {{1}, {1, 1}, {1, 2, 3}, {0.5, 10, 2.25}, {3, 0, 1}, {1, 1, 1, 1, 1, 1}, {-1}, {0, 0}};
        s.append("pub const WEIGHTS: &[&[f64]] = &[");
        StringJoiner wj = new StringJoiner(", ");
        for (double[] w : weights) {
            StringJoiner j = new StringJoiner(", ", "&[", "]");
            for (double v : w) j.add(Double.toString(v));
            wj.add(j.toString());
        }
        s.append(wj).append("];\n\n");

        s.append("/// (x, y, z, hashToFloat bits, picked index per WEIGHTS entry, -1 = none)\n");
        s.append("pub const PICKS: &[(i32, i32, i32, u32, [i8; ").append(weights.length).append("])] = &[\n");
        for (int[] p : pos) {
            StringJoiner j = new StringJoiner(", ", "[", "]");
            for (double[] w : weights) j.add(Integer.toString(pick(w, p[0], p[1], p[2])));
            s.append("    (").append(p[0]).append(", ").append(p[1]).append(", ").append(p[2]).append(", ")
                    .append(f(hashToFloat(p[0], p[1], p[2]))).append(", ").append(j).append("),\n");
        }
        s.append("];\n\n");

        float[] xs = {0, 90, 180, 270, 22.5f, -45};
        float[] zs = {0, 90, 45};
        s.append("/// (x, y, z, Variant.transformMatrix bits)\n");
        s.append("pub const MATRICES: &[(f32, f32, f32, [u32; 16])] = &[\n");
        for (float x : xs) for (float y : xs) for (float z : zs) {
            MatrixM4f m = new MatrixM4f()
                    .translate(-0.5f, -0.5f, -0.5f)
                    .rotateYXZ(-x, -y, -z)
                    .translate(0.5f, 0.5f, 0.5f);
            StringJoiner j = new StringJoiner(", ", "[", "]");
            for (float v : new float[]{m.m00, m.m01, m.m02, m.m03, m.m10, m.m11, m.m12, m.m13, m.m20, m.m21, m.m22, m.m23, m.m30, m.m31, m.m32, m.m33}) j.add(f(v));
            s.append("    (").append(x).append(", ").append(y).append(", ").append(z).append(", ").append(j).append("),\n");
        }
        s.append("];\n");
        System.out.print(s);
    }
}
