import com.flowpowered.math.GenericMath;
import de.bluecolored.bluemap.core.util.math.*;

import java.nio.file.*;
import java.util.*;

// Emits bm-resources tests/data/color.rs: args = <output file>.
// The calculator chain (ColorMap.getColor, BlockColorCalculatorType, GrassColorModifier, BlendedBlockColorCalculator)
// is transcribed line by line because those classes need lombok and the world API; the Color, SimplexNoise,
// java.util.Random and GenericMath they run on are the real classes.
public class ColorRef {
    static String f(float v) { return String.format("0x%08x", Float.floatToRawIntBits(v)); }
    static String col(Color c) { return "[" + f(c.r) + ", " + f(c.g) + ", " + f(c.b) + ", " + f(c.a) + ", " + (c.premultiplied ? 1 : 0) + "]"; }

    static int pixel(int i, int salt) { return (i * 0x9E3779B1) ^ (i >>> 3) ^ salt; }
    static int[] map(int salt) { int[] m = new int[65536]; for (int i = 0; i < m.length; i++) m[i] = pixel(i, salt); return m; }

    static final int[] FOLIAGE = map(0), GRASS = map(0x5A5A5A);
    static final SimplexNoise SWAMP_GRASS_NOISE = new SimplexNoise(new Random(2345L));

    record B(float temperature, float downfall, int foliage, int grass, int modifier, int water) {
        Color overlay(int argb) { return argb == 0 ? new Color().premultiplied() : new Color().set(argb).premultiplied(); }
        Color waterColor() { Color c = new Color().set(water); c.a = 1f; return c; }
    }

    static final B[] BIOMES = {
        new B(0.5f, 0.5f, 0, 0, 0, 0xff3f76e4),
        new B(0.8f, 0.9f, 0xff6a7039, 0, 2, 0xff617b64),
        new B(0.7f, 0.8f, 0, 0, 1, 0xff3f76e4),
        new B(2.0f, 0.0f, 0xff9e814d, 0xff90814d, 0, 0x8032a598),
        new B(-0.5f, 0.4f, 0, 0x80ff0000, 0, 0x003d57d6),
        new B(0.95f, 0.8f, 0x40123456, 0, 2, 0xff0d8ae3),
        new B(0.25f, 1.5f, 0, 0, 1, 0xff3938c9),
    };

    static int biomeAt(int x, int y, int z) { return Math.floorMod(x * 7 + z * 13 + y * 3 + (x >> 2) * 5, BIOMES.length); }

    static Color colorMap(int[] map, int def, B b, Color target) {
        if (map == null) return target.set(new Color().set(def, true).premultiplied());
        double temperature = GenericMath.clamp(b.temperature, 0.0, 1.0);
        double downfall = GenericMath.clamp(b.downfall, 0.0, 1.0);
        downfall *= temperature;
        int x = (int) ((1.0 - temperature) * 255.0);
        int y = (int) ((1.0 - downfall) * 255.0);
        return target.set(map[y << 8 | x] | 0xFF000000, true);
    }

    static Color sample(int type, int x, int y, int z, Color target) {
        return sample(type, BIOMES[biomeAt(x, y, z)], x, z, target);
    }

    static Color sample(int type, B b, int x, int z, Color target) {
        switch (type) {
            case 0 -> colorMap(FOLIAGE, 0xff48B518, b, target).overlay(b.overlay(b.foliage));
            case 1 -> colorMap(null, 0xff8f5f33, b, target).overlay(b.overlay(b.foliage));
            case 2 -> {
                colorMap(GRASS, 0xff52952f, b, target).overlay(b.overlay(b.grass));
                if (b.modifier == 1) target.set(((target.getInt() & 0xfefefe) + 0x28340a >> 1) | 0xff000000, true);
                if (b.modifier == 2) {
                    double n = SWAMP_GRASS_NOISE.getValue(x * 0.0225, z * 0.0225);
                    target.set(n < -0.1 ? 0xff4c763c : 0xff6a7039, true);
                }
            }
            default -> target.set(b.waterColor());
        }
        return target;
    }

    static Color blended(int type, int x, int y, int z) {
        Color target = new Color().set(0, 0, 0, 0, true), delegate = new Color();
        for (int dy = -1; dy <= 1; dy++)
            for (int dx = -2; dx <= 2; dx++)
                for (int dz = -2; dz <= 2; dz++)
                    target.add(sample(type, x + dx, y + dy, z + dz, delegate));
        return target.flatten();
    }

    public static void main(String[] args) throws Exception {
        StringBuilder s = new StringBuilder("// @generated by ColorRef.java (BlueMap util.math + flow-math 1.0.3, JDK 25). Do not edit.\n\n");
        s.append("/// (temperature, downfall, foliage ARGB or 0, grass ARGB or 0, modifier 0 none/1 dark_forest/2 swamp, water ARGB)\n");
        s.append("pub const BIOMES: &[(u32, u32, u32, u32, u8, u32)] = &[\n");
        for (B b : BIOMES)
            s.append(String.format("    (%s, %s, 0x%08x, 0x%08x, %d, 0x%08x),\n", f(b.temperature), f(b.downfall), b.foliage, b.grass, b.modifier, b.water));
        s.append("];\n\n");

        s.append("/// Unblended (type 0 foliage, 1 dry_foliage, 2 grass, 3 water; x; z; biome; [r, g, b, a, premultiplied])\n");
        s.append("pub const SAMPLES: &[(u8, i32, i32, usize, [u32; 5])] = &[\n");
        int[][] xz = {{0, 0}, {100, -40}, {-1234, 567}, {31, 4000}, {-77, -77}, {2048, 1}};
        for (int type = 0; type < 4; type++)
            for (int bi = 0; bi < BIOMES.length; bi++)
                for (int[] p : xz)
                    s.append(String.format("    (%d, %d, %d, %d, %s),\n", type, p[0], p[1], bi, col(sample(type, BIOMES[bi], p[0], p[1], new Color()))));
        s.append("];\n\n");

        s.append("/// Blended (type, x, y, z, [r, g, b, a, premultiplied])\n");
        s.append("pub const BLENDED: &[(u8, i32, i32, i32, [u32; 5])] = &[\n");
        Random r = new Random(7);
        for (int i = 0; i < 40; i++) {
            int x = r.nextInt(4000) - 2000, y = r.nextInt(380) - 64, z = r.nextInt(4000) - 2000;
            for (int type = 0; type < 4; type++)
                s.append(String.format("    (%d, %d, %d, %d, %s),\n", type, x, y, z, col(blended(type, x, y, z))));
        }
        s.append("];\n\n");

        s.append("/// ColorMap lookups on the foliage map (temperature, downfall, [r, g, b, a, premultiplied])\n");
        s.append("pub const LOOKUPS: &[(u32, u32, [u32; 5])] = &[\n");
        float[] ts = {0f, 1f, 0.5f, 0.3f, 0.8f, 0.95f, -1f, 2f, Float.NaN, 0.001f, 0.999f};
        for (float t : ts)
            for (float d : ts)
                s.append(String.format("    (%s, %s, %s),\n", f(t), f(d), col(colorMap(FOLIAGE, 0, new B(t, d, 0, 0, 0, 0), new Color()))));
        s.append("];\n");
        Files.writeString(Path.of(args[0]), s.toString());
    }
}
