import java.nio.file.*;
import java.util.*;

// Emits bm-java test data for Double/Float.toString and (Concurrent)HashMap<String,_> iteration order. arg = <bm-java tests/data dir>
public class JdkRef {
    static final String HEADER = "// @generated by JdkRef.java (JDK 25). Do not edit.\n\n";

    public static void main(String[] args) throws Exception {
        Path dir = Path.of(args[0]);
        Files.writeString(dir.resolve("fmt.rs"), HEADER + doubles() + "\n" + floats());
        Files.writeString(dir.resolve("hash_map.rs"), HEADER + hashOrders());
        Files.writeString(dir.resolve("concurrent_hash_map.rs"), HEADER + concurrentOrders());
    }

    static List<Double> doubleInputs() {
        List<Double> v = new ArrayList<>(List.of(0.0, -0.0, 1.0, -1.0, 0.1, 0.5, 2.0, 1e-3, 9.999e-4, 1e7, 9999999.0,
                1e23, 2e23, 1e22, 123456789.0, 1e-5, Double.MIN_VALUE, Double.MAX_VALUE, Double.MIN_NORMAL,
                4.9e-324, 1.0E-322, (double) 0.1f, (double) 0.6f, (double) (125 / 255f), (double) (171 / 255f),
                Double.NaN, Double.POSITIVE_INFINITY, Double.NEGATIVE_INFINITY));
        for (int e = -330; e <= 310; e++) { v.add(Math.pow(10, e)); v.add(2 * Math.pow(10, e)); v.add(9.5 * Math.pow(10, e)); }
        for (int e = -1074; e <= 1023; e += 7) v.add(Math.scalb(1.0, e));
        for (int i = 0; i <= 255; i++) v.add((double) (i / 255f));
        Random r = new Random(1);
        for (int i = 0; i < 800; i++) {
            double d = Double.longBitsToDouble(r.nextLong());
            if (!Double.isNaN(d)) v.add(d);
        }
        for (int i = 0; i < 400; i++) v.add(r.nextInt(2000000) / Math.pow(10, r.nextInt(12)));
        return v;
    }

    static String doubles() {
        StringBuilder s = new StringBuilder("/// (Double.doubleToRawLongBits, Double.toString)\npub const DOUBLES: &[(u64, &str)] = &[\n");
        for (double d : doubleInputs())
            s.append(String.format("    (0x%016x, \"%s\"),\n", Double.doubleToRawLongBits(d), Double.toString(d)));
        return s.append("];\n").toString();
    }

    static String floats() {
        List<Float> v = new ArrayList<>(List.of(0f, -0f, 1f, 0.1f, 0.6f, 1e-3f, 9.999e-4f, 1e7f, 9999999f, Float.MIN_VALUE,
                Float.MAX_VALUE, Float.MIN_NORMAL, 2.8e-45f, 1e10f, Float.NaN, Float.POSITIVE_INFINITY, Float.NEGATIVE_INFINITY));
        for (int e = -45; e <= 38; e++) { v.add((float) Math.pow(10, e)); v.add(2 * (float) Math.pow(10, e)); }
        for (int e = -149; e <= 127; e += 3) v.add(Math.scalb(1f, e));
        for (int i = 0; i <= 255; i++) v.add(i / 255f);
        Random r = new Random(2);
        for (int i = 0; i < 800; i++) {
            float f = Float.intBitsToFloat(r.nextInt());
            if (!Float.isNaN(f)) v.add(f);
        }
        for (int i = 0; i < 400; i++) v.add((float) (r.nextInt(200000) / Math.pow(10, r.nextInt(8))));
        StringBuilder s = new StringBuilder("/// (Float.floatToRawIntBits, Float.toString)\npub const FLOATS: &[(u32, &str)] = &[\n");
        for (float f : v) s.append(String.format("    (0x%08x, \"%s\"),\n", Float.floatToRawIntBits(f), Float.toString(f)));
        return s.append("];\n").toString();
    }

    static String hashOrders() {
        StringBuilder s = new StringBuilder("/// (insertion order, iteration order of a fresh HashMap)\npub const ORDERS: &[(&[&str], &[&str])] = &[\n");
        Random r = new Random(3);
        String alphabet = "abcdefghijklmnopqrstuvwxyz0123456789_";
        for (int n = 1; n <= 60; n++) {
            List<String> keys = new ArrayList<>();
            for (int i = 0; i < n; i++) {
                StringBuilder k = new StringBuilder();
                for (int l = 1 + r.nextInt(12); l > 0; l--) k.append(alphabet.charAt(r.nextInt(alphabet.length())));
                keys.add(k.toString());
            }
            Map<String, Integer> map = new HashMap<>();
            for (String k : keys) map.put(k, 0);
            s.append("    (").append(list(keys)).append(", ").append(list(map.keySet())).append("),\n");
        }
        return s.append("];\n").toString();
    }

    static String concurrentOrders() {
        StringBuilder s = new StringBuilder("/// (insertion order, filled by putAll instead of put, iteration order of a fresh ConcurrentHashMap)\n"
                + "pub const ORDERS: &[(&[&str], bool, &[&str])] = &[\n");
        Random r = new Random(4);
        String alphabet = "abcAB_";
        String[] colliding = {"Aa", "BB", "AaAa", "AaBB", "BBAa", "BBBB"};
        for (int n = 1; n <= 80; n++) {
            LinkedHashMap<String, Integer> keys = new LinkedHashMap<>();
            while (keys.size() < n) {
                StringBuilder k = new StringBuilder();
                if (r.nextInt(4) == 0) k.append(colliding[r.nextInt(colliding.length)]);
                for (int l = r.nextInt(5); l > 0; l--) k.append(alphabet.charAt(r.nextInt(alphabet.length())));
                keys.put(k.toString(), 0);
            }
            for (boolean putAll : new boolean[] {false, true}) {
                java.util.concurrent.ConcurrentHashMap<String, Integer> map = new java.util.concurrent.ConcurrentHashMap<>();
                if (putAll) map.putAll(keys); else for (String k : keys.keySet()) map.put(k, 0);
                s.append("    (").append(list(keys.keySet())).append(", ").append(putAll).append(", ").append(list(map.keySet())).append("),\n");
            }
        }
        return s.append("];\n").toString();
    }

    static String list(Collection<String> c) {
        StringJoiner j = new StringJoiner(", ", "&[", "]");
        for (String k : c) j.add("\"" + k + "\"");
        return j.toString();
    }
}
