import com.flowpowered.math.vector.*;
import de.bluecolored.bluemap.api.math.Shape;
import de.bluecolored.bluemap.core.map.mask.*;
import de.bluecolored.bluemap.core.util.Tristate;

import java.nio.file.*;
import java.util.*;

// Runs BlueMap's real mask classes (from the 5.28 CLI jar) over random queries. arg = output .rs file.
// Spec grammar (shared with bm-map/tests/mask_ref.rs): layers "+type args" / "-type args" (subtract);
// box minX minY minZ maxX maxY maxZ | circle cx cz r minY maxY | ellipse cx cz rx rz minY maxY |
// poly minY maxY x1 z1 x2 z2 ... | blur size ( layers )
public class MaskRef {
    static final int MIN = Integer.MIN_VALUE, MAX = Integer.MAX_VALUE;
    static final String[] SPECS = {
            "",
            "+box -2147483648 -2147483648 -2147483648 2147483647 2147483647 2147483647",
            "+box -2147483648 -2147483648 -2147483648 2147483647 2147483647 2147483647 -box -2147483648 90 -2147483648 2147483647 127 2147483647",
            "+box -20 -10 -30 40 64 25",
            "-box -20 0 -20 20 255 20",
            "+circle 0.0 0.0 50.0 -2147483648 2147483647",
            "+circle 10.5 -3.25 17.3 0 100",
            "+circle 0.0 0.0 1.7976931348623157E308 -2147483648 2147483647",
            "+ellipse -5.0 7.5 40.0 12.5 -64 320",
            "+poly -2147483648 2147483647 0.0 0.0 60.0 10.0 30.0 70.0 -40.0 40.0",
            "+poly -10 150 0.0 -50.0 12.0 -12.0 50.0 0.0 12.0 12.0 0.0 50.0 -12.0 12.0 -50.0 0.0 -12.0 -12.0",
            "+poly 0 64 -32.0 -32.0 32.0 -32.0 32.0 32.0 0.0 32.0 0.0 0.0 -32.0 0.0",
            "+poly -2147483648 2147483647 -7.5 -3.3 41.2 -9.9 13.7 28.1",
            "+circle 0.0 0.0 80.0 -2147483648 2147483647 -box -10 -2147483648 -10 10 2147483647 10 +poly 0 100 -5.0 -5.0 5.0 -5.0 0.0 5.0",
            "+blur 5 ( +box -30 -2147483648 -30 30 2147483647 30 )",
            "+blur 3 ( +circle 0.0 0.0 40.0 -2147483648 2147483647 -box 0 -2147483648 0 50 2147483647 50 )",
            "+box -60 -2147483648 -60 60 2147483647 60 -blur 4 ( +circle 5.0 5.0 20.0 -2147483648 2147483647 )",
            "+blur 0 ( +box -16 0 -16 15 255 15 )",
            "-circle 0.0 0.0 30.0 -2147483648 2147483647 +ellipse 0.0 0.0 10.0 20.0 50 60",
    };

    static int pos;
    static String[] tok;

    static CombinedMask parse(String spec) {
        tok = spec.isBlank() ? new String[0] : spec.trim().split("\\s+");
        pos = 0;
        return layers();
    }

    static CombinedMask layers() {
        CombinedMask combined = new CombinedMask();
        while (pos < tok.length && !tok[pos].equals(")")) {
            String t = tok[pos++];
            boolean value = t.charAt(0) == '+';
            combined.add(mask(t.substring(1)), value);
        }
        pos++;
        return combined;
    }

    static int i() { return Integer.parseInt(tok[pos++]); }
    static double d() { return Double.parseDouble(tok[pos++]); }

    static Mask mask(String type) {
        switch (type) {
            case "box": return new BoxMask(new Vector3i(i(), i(), i()), new Vector3i(i(), i(), i()));
            case "circle": return new EllipseMask(new Vector2d(d(), d()), d(), i(), i());
            case "ellipse": return new EllipseMask(new Vector2d(d(), d()), d(), d(), i(), i());
            case "poly": {
                int minY = i(), maxY = i();
                List<Vector2d> pts = new ArrayList<>();
                while (pos < tok.length && tok[pos].matches("-?[0-9].*")) pts.add(new Vector2d(d(), d()));
                return new PolygonMask(new Shape(pts), minY, maxY);
            }
            case "blur": {
                int size = i();
                pos++; // (
                CombinedMask inner = layers();
                return size > 0 ? new BlurMask(inner, size) : inner;
            }
            default: throw new IllegalArgumentException(type);
        }
    }

    static int ts(Tristate t) { return t == Tristate.TRUE ? 1 : t == Tristate.FALSE ? -1 : 0; }

    static int coord(Random r) {
        int k = r.nextInt(40);
        if (k == 0) return MIN + r.nextInt(100);
        if (k == 1) return MAX - r.nextInt(100);
        return r.nextInt(200) - 100;
    }

    static int[] area(Random r) {
        int x = r.nextInt(200) - 100, z = r.nextInt(200) - 100;
        int w = r.nextInt(4) == 0 ? 16 : r.nextInt(64), h = r.nextInt(4) == 0 ? 16 : r.nextInt(64);
        boolean fullY = r.nextBoolean();
        int y = r.nextInt(300) - 100;
        return new int[]{x, fullY ? MIN : y, z, x + w, fullY ? MAX : y + r.nextInt(100), z + h};
    }

    public static void main(String[] args) throws Exception {
        StringBuilder s = new StringBuilder("// @generated by MaskRef.java (BlueMap 5.28 CLI jar, JDK 25). Do not edit.\n\n");
        s.append("pub type Point = (i32, i32, i32, bool);\n\n");
        s.append("pub struct Scenario {\n    pub spec: &'static str,\n    pub points: &'static [Point],\n")
         .append("    pub boxes: &'static [([i32; 6], i8)],\n    pub edges: &'static [([i32; 4], bool)],\n")
         .append("    /// (area, submask kind: A=ALL N=NONE C=CombinedMask O=other, combined layer count, points tested on the submask)\n")
         .append("    pub subs: &'static [([i32; 6], char, i32, &'static [Point])],\n}\n\n")
         .append("pub const SCENARIOS: &[Scenario] = &[\n");
        Random r = new Random(42);
        for (String spec : SPECS) {
            Mask m = parse(spec);
            s.append("    Scenario {\n        spec: \"").append(spec).append("\",\n        points: &[");
            for (int n = 0; n < 200; n++) {
                int x = coord(r), y = coord(r), z = coord(r);
                s.append(String.format("(%d, %d, %d, %b), ", x, y, z, m.test(x, y, z)));
            }
            s.append("],\n        boxes: &[");
            for (int n = 0; n < 120; n++) {
                int[] a = area(r);
                s.append(String.format("([%d, %d, %d, %d, %d, %d], %d), ", a[0], a[1], a[2], a[3], a[4], a[5],
                        ts(m.test(a[0], a[1], a[2], a[3], a[4], a[5]))));
            }
            s.append("],\n        edges: &[");
            for (int n = 0; n < 120; n++) {
                int[] a = area(r);
                s.append(String.format("([%d, %d, %d, %d], %b), ", a[0], a[2], a[3], a[5], m.isEdge(a[0], a[2], a[3], a[5])));
            }
            s.append("],\n        subs: &[\n");
            for (int n = 0; n < 24; n++) {
                int[] a = area(r);
                Mask sub = m.submask(a[0], a[1], a[2], a[3], a[4], a[5]);
                char kind = sub == Mask.ALL ? 'A' : sub == Mask.NONE ? 'N' : sub instanceof CombinedMask ? 'C' : 'O';
                int layers = sub instanceof CombinedMask c ? c.size() : -1;
                s.append(String.format("            ([%d, %d, %d, %d, %d, %d], '%c', %d, &[", a[0], a[1], a[2], a[3], a[4], a[5], kind, layers));
                for (int p = 0; p < 12; p++) {
                    int x = a[0] + r.nextInt(a[3] - a[0] + 1), z = a[2] + r.nextInt(a[5] - a[2] + 1);
                    int y = a[1] == MIN ? r.nextInt(400) - 100 : a[1] + r.nextInt(a[4] - a[1] + 1);
                    s.append(String.format("(%d, %d, %d, %b), ", x, y, z, sub.test(x, y, z)));
                }
                s.append("]),\n");
            }
            s.append("        ],\n    },\n");
        }
        s.append("];\n");
        Files.writeString(Path.of(args[0]), s.toString());
    }
}
