import com.flowpowered.math.TrigMath;
import de.bluecolored.bluemap.core.util.math.*;

import java.lang.reflect.Field;
import java.nio.file.*;
import java.util.*;

// Emits Rust test-data modules: args = <bm-java tests/data dir> <bm-math tests/data dir>
public class MathRef {
    static final String HEADER = "// @generated by MathRef.java (BlueMap util.math + flow-math 1.0.3 TrigMath, JDK 25). Do not edit.\n\n";

    static String f(float v) { return String.format("0x%08x", Float.floatToRawIntBits(v)); }
    static String d(double v) { return String.format("0x%016x", Double.doubleToRawLongBits(v)); }
    static String fa(float... v) { StringJoiner j = new StringJoiner(", ", "[", "]"); for (float x : v) j.add(f(x)); return j.toString(); }
    static String da(double... v) { StringJoiner j = new StringJoiner(", ", "[", "]"); for (double x : v) j.add(d(x)); return j.toString(); }
    static String m4(MatrixM4f m) { return fa(m.m00, m.m01, m.m02, m.m03, m.m10, m.m11, m.m12, m.m13, m.m20, m.m21, m.m22, m.m23, m.m30, m.m31, m.m32, m.m33); }
    static String m3(MatrixM3f m) { return fa(m.m00, m.m01, m.m02, m.m10, m.m11, m.m12, m.m20, m.m21, m.m22); }
    static String col(Color c) { return "[" + f(c.r) + ", " + f(c.g) + ", " + f(c.b) + ", " + f(c.a) + ", " + (c.premultiplied ? 1 : 0) + "]"; }

    // packs runs of one-line "    (...)," entries into lines of at most WIDTH chars
    static final int WIDTH = 160;
    static void write(Path p, String s) throws Exception {
        StringBuilder out = new StringBuilder(HEADER);
        StringBuilder line = new StringBuilder();
        for (String l : s.split("\n", -1)) {
            boolean entry = l.startsWith("    (") && l.endsWith("),");
            if (entry && line.length() > 0 && line.length() + l.length() - 3 <= WIDTH) { line.append(l.substring(3)); continue; }
            if (line.length() > 0) { out.append(line).append("\n"); line.setLength(0); }
            if (entry) line.append(l); else out.append(l).append("\n");
        }
        if (line.length() > 0) out.append(line).append("\n");
        Files.writeString(p, out.toString().stripTrailing() + "\n");
    }

    public static void main(String[] args) throws Exception {
        write(Path.of(args[0], "trig.rs"), trig());
        Path m = Path.of(args[1]);
        write(m.resolve("matrix.rs"), matrix());
        write(m.resolve("vector.rs"), vector());
        write(m.resolve("color.rs"), color());
        write(m.resolve("noise.rs"), noise());
    }

    // ---------------------------------------------------------------- trig
    static String trig() throws Exception {
        StringBuilder s = new StringBuilder();
        Field tf = TrigMath.class.getDeclaredField("SIN_TABLE");
        tf.setAccessible(true);
        float[] table = (float[]) tf.get(null);
        long h = 0xcbf29ce484222325L;
        for (float v : table) h = (h ^ (Float.floatToRawIntBits(v) & 0xffffffffL)) * 0x100000001b3L;
        s.append("pub const TABLE_FINGERPRINT: u64 = ").append(String.format("0x%016x", h)).append(";\n\n");

        List<Double> angles = new ArrayList<>();
        s.append("/// (degrees, Math.toRadians)\npub const TO_RADIANS: &[(u64, u64)] = &[\n");
        for (int i = -48; i <= 48; i++) {
            double deg = i * 7.5;
            double rad = Math.toRadians(deg);
            s.append("    (").append(d(deg)).append(", ").append(d(rad)).append("),\n");
            angles.add(rad);
            angles.add(rad * 0.5);
            angles.add((double) (float) rad);
        }
        s.append("];\n\n");
        for (int k = 0; k < 100; k++) angles.add((k - 50) * 0.2469135 + k * k * 1e-5);
        double[] edge = {0.0, -0.0, 1e-12, -1e-12, TrigMath.TWO_PI, -TrigMath.TWO_PI, TrigMath.HALF_PI, Math.PI, 1e6, -1e6, 1e10, -1e10,
                Double.NaN, Double.POSITIVE_INFINITY, Double.NEGATIVE_INFINITY};
        for (double e : edge) angles.add(e);
        s.append("/// (angle, TrigMath.sin, TrigMath.cos)\npub const SIN_COS: &[(u64, u32, u32)] = &[\n");
        for (double a : angles) s.append("    (").append(d(a)).append(", ").append(f(TrigMath.sin(a))).append(", ").append(f(TrigMath.cos(a))).append("),\n");
        s.append("];\n\n");

        double[] vals = {0.0, -0.0, 1, -1, 0.5, -3, 1e-9, -1e-9, 1e9, 0.7071, 0.3, -0.41};
        s.append("/// (y, x, TrigMath.atan2)\npub const ATAN2: &[(u64, u64, u64)] = &[\n");
        for (double y : vals) for (double x : vals) s.append("    (").append(d(y)).append(", ").append(d(x)).append(", ").append(d(TrigMath.atan2(y, x))).append("),\n");
        s.append("];\n\n");

        List<Double> arc = new ArrayList<>();
        for (int i = -24; i <= 24; i++) arc.add(i * 0.05);
        for (double e : new double[]{0.7, 0.70001, 0.4142, 0.41422, 2.4142, 2.41422, 5, -5, 1e9, -0.0}) arc.add(e);
        s.append("/// (value, TrigMath.asin, TrigMath.acos, TrigMath.atan)\npub const ARC: &[(u64, u64, u64, u64)] = &[\n");
        for (double v : arc) s.append("    (").append(d(v)).append(", ").append(d(TrigMath.asin(v))).append(", ").append(d(TrigMath.acos(v))).append(", ").append(d(TrigMath.atan(v))).append("),\n");
        s.append("];\n");
        return s.toString();
    }

    // ---------------------------------------------------------------- matrix
    static double[] eulerXYZ(float pitch, float yaw, float roll) {
        double halfPitch = Math.toRadians(pitch) * 0.5, sx = TrigMath.sin(halfPitch), cx = TrigMath.cos(halfPitch),
                halfYaw = Math.toRadians(yaw) * 0.5, sy = TrigMath.sin(halfYaw), cy = TrigMath.cos(halfYaw),
                halfRoll = Math.toRadians(roll) * 0.5, sz = TrigMath.sin(halfRoll), cz = TrigMath.cos(halfRoll),
                cycz = cy * cz, sysz = sy * sz, sycz = sy * cz, cysz = cy * sz;
        return new double[]{sx * cycz + cx * sysz, cx * sycz - sx * cysz, cx * cysz + sx * sycz, cx * cycz - sx * sysz};
    }

    static double[] eulerZYX(float pitch, float yaw, float roll) {
        double halfPitch = Math.toRadians(pitch) * 0.5, sx = TrigMath.sin(halfPitch), cx = TrigMath.cos(halfPitch),
                halfYaw = Math.toRadians(yaw) * 0.5, sy = TrigMath.sin(halfYaw), cy = TrigMath.cos(halfYaw),
                halfRoll = Math.toRadians(roll) * 0.5, sz = TrigMath.sin(halfRoll), cz = TrigMath.cos(halfRoll),
                cycz = cy * cz, sysz = sy * sz, sycz = sy * cz, cysz = cy * sz;
        return new double[]{cx * cycz + sx * sysz, sx * cycz - cx * sysz, cx * sycz + sx * cysz, cx * cysz - sx * sycz};
    }

    static double[] eulerYXZ(float pitch, float yaw, float roll) {
        double halfPitch = Math.toRadians(pitch) * 0.5, sx = TrigMath.sin(halfPitch), cx = TrigMath.cos(halfPitch),
                halfYaw = Math.toRadians(yaw) * 0.5, sy = TrigMath.sin(halfYaw), cy = TrigMath.cos(halfYaw),
                halfRoll = Math.toRadians(roll) * 0.5, sz = TrigMath.sin(halfRoll), cz = TrigMath.cos(halfRoll),
                cysx = cy * sx, sycx = sy * cx, sysx = sy * sx, cycx = cy * cx;
        return new double[]{cysx * cz + sycx * sz, sycx * cz - cysx * sz, cycx * sz - sysx * cz, cycx * cz + sysx * sz};
    }

    static double[] axisAngle(float angle, float axisX, float axisY, float axisZ) {
        double halfAngle = Math.toRadians(angle) * 0.5;
        double q = TrigMath.sin(halfAngle) / Math.sqrt(axisX * axisX + axisY * axisY + axisZ * axisZ);
        double qx = axisX * q, qy = axisY * q, qz = axisZ * q, qw = TrigMath.cos(halfAngle),
                qLength = Math.sqrt(qx * qx + qy * qy + qz * qz + qw * qw);
        qx /= qLength; qy /= qLength; qz /= qLength; qw /= qLength;
        return new double[]{qx, qy, qz, qw};
    }

    static MatrixM4f base4() { return new MatrixM4f().translate(1.25f, -3.5f, 7f).scale(2f, 0.5f, -1f); }
    static MatrixM3f base3() { return new MatrixM3f().translate(0.25f, -0.75f).scale(1.5f, -2f, 1f); }

    static MatrixM4f variant(float x, float y, float z) {
        return new MatrixM4f().translate(-0.5f, -0.5f, -0.5f).rotateYXZ(-x, -y, -z).translate(0.5f, 0.5f, 0.5f);
    }

    // Rotation.init after the angle/axis -> x/y/z step
    static MatrixM4f modelRotation(float ox, float oy, float oz, float x, float y, float z, boolean rescale) {
        MatrixM4f matrix = new MatrixM4f();
        if (x != 0 || y != 0 || z != 0) {
            matrix.translate(-ox, -oy, -oz);
            matrix.rotateYXZ(x, y, z);
            if (rescale) {
                VectorM3f axisVector = new VectorM3f(0, 0, 0);
                float sX = 1f / axisVector.set(1, 0, 0).rotateAndScale(matrix).absolute().max();
                float sY = 1f / axisVector.set(0, 1, 0).rotateAndScale(matrix).absolute().max();
                float sZ = 1f / axisVector.set(0, 0, 1).rotateAndScale(matrix).absolute().max();
                matrix.identity();
                matrix.translate(-ox, -oy, -oz);
                matrix.scale(sX, sY, sZ);
                matrix.rotateYXZ(x, y, z);
            }
            matrix.translate(ox, oy, oz);
        }
        return matrix;
    }

    static final float[][] EULER = {{0, 0, 0}, {22.5f, 0, 0}, {0, 22.5f, 0}, {0, 0, 22.5f}, {45, 0, 0}, {0, 45, 0}, {0, 0, 45},
            {-22.5f, -45, 0}, {90, 180, 270}, {-90, -270, 0}, {33.3f, -71, 12.5f}, {-147.25f, 89.9f, 400}, {0, 180 - 37.5f, 0},
            {1e-3f, -1e-3f, 359.99f}};
    static final float[][] AXIS_ANGLE = {{90, 0, 1, 0}, {-22.5f, 1, 0, 0}, {45, 0, 0, 1}, {33.3f, 1, 1, 0}, {-71, 0.3f, -2, 5},
            {180, 0, 0, 1}, {-45, 0, 0, 1}, {-135, 0, 0, 1}};
    static final float[] ROT_ANGLES = {-45, -22.5f, 22.5f, 45, 30, -67.5f};
    static final float[][] ORIGINS = {{8, 8, 8}, {3.5f, 1, 12.25f}};
    static final float[][] ROT_XYZ = {{22.5f, 45, 0}, {-30, 0, 15}, {0, -90, 22.5f}};

    static String matrix() {
        StringBuilder s = new StringBuilder();
        float[] q = {0, 90, 180, 270};
        s.append("/// Variant transform: ([x, y, z], matrix)\npub const VARIANT: &[([u32; 3], [u32; 16])] = &[\n");
        for (float x : q) for (float y : q) for (float z : q)
            s.append("    (").append(fa(x, y, z)).append(", ").append(m4(variant(x, y, z))).append("),\n");
        s.append("];\n\n");

        s.append("/// ([pitch, yaw, roll], quats xyz/zyx/yxz, base4 rotated xyz/zyx/yxz, base3 rotated xyz/zyx/yxz)\n");
        s.append("pub const EULER: &[([u32; 3], [[u64; 4]; 3], [[u32; 16]; 3], [[u32; 9]; 3])] = &[\n");
        for (float[] e : EULER) {
            s.append("    (").append(fa(e)).append(",\n");
            s.append("     [").append(da(eulerXYZ(e[0], e[1], e[2]))).append(", ").append(da(eulerZYX(e[0], e[1], e[2]))).append(", ").append(da(eulerYXZ(e[0], e[1], e[2]))).append("],\n");
            s.append("     [").append(m4(base4().rotateXYZ(e[0], e[1], e[2]))).append(",\n      ").append(m4(base4().rotateZYX(e[0], e[1], e[2]))).append(",\n      ").append(m4(base4().rotateYXZ(e[0], e[1], e[2]))).append("],\n");
            s.append("     [").append(m3(base3().rotateXYZ(e[0], e[1], e[2]))).append(", ").append(m3(base3().rotateZYX(e[0], e[1], e[2]))).append(", ").append(m3(base3().rotateYXZ(e[0], e[1], e[2]))).append("]),\n");
        }
        s.append("];\n\n");

        s.append("/// ([angle, axis x, y, z], quat, base4 rotated, base3 rotated)\npub const AXIS_ANGLE: &[([u32; 4], [u64; 4], [u32; 16], [u32; 9])] = &[\n");
        for (float[] a : AXIS_ANGLE)
            s.append("    (").append(fa(a)).append(", ").append(da(axisAngle(a[0], a[1], a[2], a[3]))).append(",\n     ")
                    .append(m4(base4().rotate(a[0], a[1], a[2], a[3]))).append(", ").append(m3(base3().rotate(a[0], a[1], a[2], a[3]))).append("),\n");
        s.append("];\n\n");

        s.append("/// Model element rotation: ([origin x, y, z, rot x, y, z], rescale, matrix)\npub const MODEL_ROTATION: &[([u32; 6], bool, [u32; 16])] = &[\n");
        List<float[]> rots = new ArrayList<>();
        for (float a : ROT_ANGLES) for (int axis = 0; axis < 3; axis++) { float[] r = new float[3]; r[axis] = a; rots.add(r); }
        rots.addAll(Arrays.asList(ROT_XYZ));
        for (float[] o : ORIGINS) for (float[] r : rots) for (boolean rescale : new boolean[]{false, true})
            s.append("    (").append(fa(o[0], o[1], o[2], r[0], r[1], r[2])).append(", ").append(rescale).append(", ")
                    .append(m4(modelRotation(o[0], o[1], o[2], r[0], r[1], r[2], rescale))).append("),\n");
        s.append("];\n\n");

        MatrixM3f m = base3().rotate(33.3f, 0, 0, 1).rotateYXZ(10, 20, 30);
        s.append("pub const M3_CHAIN: [u32; 9] = ").append(m3(m)).append(";\n");
        s.append("pub const M3_DET: u32 = ").append(f(m.determinant())).append(";\n");
        s.append("pub const M3_INVERTED: [u32; 9] = ").append(m3(new MatrixM3f().set(m.m00, m.m01, m.m02, m.m10, m.m11, m.m12, m.m20, m.m21, m.m22).invert())).append(";\n");
        s.append("pub const M3_MULTIPLIED: [u32; 9] = ").append(m3(m.multiply(0.5f, -1.25f, 3f, 7f, 0.1f, -0.3f, 2.5f, 8f, -9.75f))).append(";\n");
        MatrixM4f m4 = base4().rotateYXZ(-22.5f, -45, 0);
        s.append("pub const M4_MULTIPLIED: [u32; 16] = ").append(m4(m4.multiply(0.5f, -1.25f, 3f, 7f, 0.1f, -0.3f, 2.5f, 8f, -9.75f, 1f, 2f, 3f, 0.2f, 0.4f, 0.6f, 1.1f))).append(";\n");
        s.append("pub const M4_MULTIPLIED_TO_M3: [u32; 16] = ").append(m4(m4.multiplyTo(base3().rotate(33.3f, 0, 0, 1).rotateYXZ(10, 20, 30)))).append(";\n");
        return s.toString();
    }

    // ---------------------------------------------------------------- vector
    static String vector() {
        StringBuilder s = new StringBuilder();
        float[][] pts = {{0, 0, 0}, {1, 1, 1}, {0.25f, 0.75f, 0.5f}, {16, 0, 3}, {-0.5f, 2.25f, -7.125f}, {0.1f, 0.2f, 0.3f}};
        MatrixM4f[] mats = {variant(0, 90, 0), variant(90, 270, 0), base4().rotateYXZ(-22.5f, -45, 0), modelRotation(8, 8, 8, 0, 0, 22.5f, true)};
        MatrixM3f m3 = base3().rotate(33.3f, 0, 0, 1).rotateYXZ(10, 20, 30);
        s.append("/// Matrices are VARIANT(0,90,0), VARIANT(90,270,0), base4.rotate_yxz(-22.5,-45,0), model rotation z 22.5 rescaled at 8.\n");
        s.append("/// (matrix index, point, transform, rotate_and_scale, transform_m3 by M3_CHAIN)\n");
        s.append("pub const TRANSFORM: &[(usize, [u32; 3], [u32; 3], [u32; 3], [u32; 3])] = &[\n");
        for (int i = 0; i < mats.length; i++) for (float[] p : pts) {
            VectorM3f a = new VectorM3f(p[0], p[1], p[2]).transform(mats[i]);
            VectorM3f b = new VectorM3f(p[0], p[1], p[2]).rotateAndScale(mats[i]);
            VectorM3f c = new VectorM3f(p[0], p[1], p[2]).transform(m3);
            s.append("    (").append(i).append(", ").append(fa(p)).append(", ").append(fa(a.x, a.y, a.z)).append(", ").append(fa(b.x, b.y, b.z)).append(", ").append(fa(c.x, c.y, c.z)).append("),\n");
        }
        s.append("];\n\n");

        s.append("/// (point, normalized, cross next, dot next, length, length_squared, max, min, abs, mul 1.5)\n");
        s.append("pub const VEC3: &[([u32; 3], [u32; 3], [u32; 3], u32, u32, u64, u32, u32, [u32; 3], [u32; 3])] = &[\n");
        for (int i = 1; i < pts.length; i++) {
            float[] p = pts[i], n = pts[(i % (pts.length - 1)) + 1];
            VectorM3f v = new VectorM3f(p[0], p[1], p[2]), w = new VectorM3f(n[0], n[1], n[2]);
            VectorM3f nv = new VectorM3f(0, 0, 0).set(v).normalize(), cr = new VectorM3f(0, 0, 0).set(v).cross(w);
            VectorM3f neg = new VectorM3f(-p[0], p[1] - 1, -p[2]), ab = new VectorM3f(0, 0, 0).set(neg).absolute(), mu = new VectorM3f(0, 0, 0).set(v).mul(1.5f);
            s.append("    (").append(fa(p)).append(", ").append(fa(nv.x, nv.y, nv.z)).append(", ").append(fa(cr.x, cr.y, cr.z)).append(", ")
                    .append(f(v.dot(w))).append(", ").append(f(v.length())).append(", ").append(d(v.lengthSquared())).append(", ")
                    .append(f(neg.max())).append(", ").append(f(neg.min())).append(", ").append(fa(ab.x, ab.y, ab.z)).append(", ").append(fa(mu.x, mu.y, mu.z)).append("),\n");
        }
        s.append("];\n\n");

        float[][] uvs = {{0, 0}, {1, 0}, {1, 1}, {0, 1}, {0.25f, 0.8125f}};
        float[] rots = {0, (float) Math.toRadians(90), (float) Math.toRadians(180), (float) Math.toRadians(270), (float) Math.toRadians(-90),
                (float) Math.toRadians(45), (float) TrigMath.atan2(1, -1), (float) TrigMath.atan2(-1, 0.0000001)};
        s.append("/// uv-lock rotation: (radians, uv, translate(-.5).rotate(cos, sin).translate(.5))\npub const UV_LOCK: &[(u32, [u32; 2], [u32; 2])] = &[\n");
        for (float r : rots) for (float[] uv : uvs) {
            float cx = TrigMath.cos(r), cy = TrigMath.sin(r);
            VectorM2f v = new VectorM2f(uv[0], uv[1]).translate(-0.5f, -0.5f).rotate(cx, cy).translate(0.5f, 0.5f);
            s.append("    (").append(f(r)).append(", ").append(fa(uv)).append(", ").append(fa(v.x, v.y)).append("),\n");
        }
        s.append("];\n\n");

        float[][] flows = {{1, 0}, {0, 1}, {-1, 0}, {0, -1}, {1, 1}, {-1, 2}, {0.3f, -0.7f}, {3, -1}, {-0.25f, -4}};
        s.append("/// (v, transform by M3_CHAIN, normalized, length, angle_to(0, -1), liquid flow degrees)\npub const VEC2: &[([u32; 2], [u32; 2], [u32; 2], u32, u32, i32)] = &[\n");
        for (float[] fl : flows) {
            VectorM2f v = new VectorM2f(fl[0], fl[1]);
            VectorM2f t = new VectorM2f(fl[0], fl[1]).transform(m3), n = new VectorM2f(fl[0], fl[1]).normalize();
            float ang = v.angleTo(0, -1);
            int deg = (int) (v.angleTo(0, -1) * TrigMath.RAD_TO_DEG);
            s.append("    (").append(fa(fl)).append(", ").append(fa(t.x, t.y)).append(", ").append(fa(n.x, n.y)).append(", ")
                    .append(f(v.length())).append(", ").append(f(ang)).append(", ").append(deg).append("),\n");
        }
        s.append("];\n\n");

        int[][] ints = {{7, -9}, {-16, 33}, {-1, -1}, {100, 0}, {-3, 4}};
        s.append("/// (v, floor_div(16, -3), div(16, -3), normalize, length, java_hash)\npub const VEC2I: &[([i32; 2], [i32; 2], [i32; 2], [i32; 2], i32, i32)] = &[\n");
        for (int[] p : ints) {
            VectorM2i v = new VectorM2i(p[0], p[1]);
            VectorM2i fd = new VectorM2i(v).floorDiv(16, -3), dv = new VectorM2i(v).div(16, -3), nv = new VectorM2i(v).normalize();
            s.append(String.format("    ([%d, %d], [%d, %d], [%d, %d], [%d, %d], %d, %d),\n", p[0], p[1], fd.x, fd.y, dv.x, dv.y, nv.x, nv.y, v.length(), v.hashCode()));
        }
        s.append("];\n");
        return s.toString();
    }

    // ---------------------------------------------------------------- color
    static String color() {
        StringBuilder s = new StringBuilder();
        String[] strs = {"#fff", "#f16", "#f168", "#ff1166", "#ff116680", "#12345678", "#ABCDEF", "#aBcDeF0a", "#000", "#0000",
                "16777215", "-1", "0", "255", "+255", "-16777216", "4278190080", "2147483647", "#12345", "#1234567", "#123456789",
                "", "#", "abc", "#ggg", "#+1234567", "#123456+f", "#-1234567", " 5", "#fff "};
        s.append("/// (input, parsed ok, get_int, [r, g, b, a, premultiplied])\npub const PARSE: &[(&str, bool, i32, [u32; 5])] = &[\n");
        for (String str : strs) {
            Color c = new Color();
            boolean ok;
            try { c.parse(str); ok = true; } catch (RuntimeException e) { ok = false; c = new Color(); }
            s.append("    (\"").append(str).append("\", ").append(ok).append(", ").append(c.getInt()).append(", ").append(col(c)).append("),\n");
        }
        s.append("];\n\n");

        int[] ints = {0xff4c763c, 0x80ff0000, 0x00000000, 0x40123456, 0xffffffff, 0xc0a0b0c0, 0x01ff8040};
        List<Color> colors = new ArrayList<>();
        for (int i : ints) for (boolean pm : new boolean[]{false, true}) colors.add(new Color().set(i, pm));

        s.append("/// (argb, premultiplied, get_int, [div 3, div 7, flatten, straight, premultiplied])\n");
        s.append("pub const SINGLE: &[(i32, bool, i32, [[u32; 5]; 5])] = &[\n");
        for (int k = 0; k < colors.size(); k++) {
            Color c = colors.get(k);
            s.append("    (").append(ints[k / 2]).append(", ").append(c.premultiplied).append(", ").append(c.getInt()).append(", [")
                    .append(col(new Color().set(c).div(3))).append(", ").append(col(new Color().set(c).div(7))).append(", ")
                    .append(col(new Color().set(c).flatten())).append(", ").append(col(new Color().set(c).straight())).append(", ")
                    .append(col(new Color().set(c).premultiplied())).append("]),\n");
        }
        s.append("];\n\n");

        s.append("/// (a index, b index, [overlay, underlay, add, multiply]); blend args are b.premultiplied(), multiply's is b as-is\n");
        s.append("pub const PAIR: &[(usize, usize, [[u32; 5]; 4])] = &[\n");
        for (int i = 0; i < colors.size(); i++) for (int j = 0; j < colors.size(); j++) {
            Color a = colors.get(i), b = colors.get(j), bp = new Color().set(b).premultiplied();
            s.append("    (").append(i).append(", ").append(j).append(", [")
                    .append(col(new Color().set(a).overlay(bp))).append(", ").append(col(new Color().set(a).underlay(bp))).append(", ")
                    .append(col(new Color().set(a).add(bp))).append(", ").append(col(new Color().set(a).multiply(b))).append("]),\n");
        }
        s.append("];\n");
        return s.toString();
    }

    // ---------------------------------------------------------------- noise
    static String noise() throws Exception {
        StringBuilder s = new StringBuilder();
        Field pf = SimplexNoise.class.getDeclaredField("p");
        pf.setAccessible(true);
        s.append("/// (seed, permutation)\npub const PERMUTATION: &[(i64, [u8; 256])] = &[\n");
        for (long seed : new long[]{2345, 0, -1, 42}) {
            int[] p = (int[]) pf.get(new SimplexNoise(new Random(seed)));
            StringJoiner j = new StringJoiner(", ", "[", "]");
            for (int v : p) j.add(Integer.toString(v));
            s.append("    (").append(seed).append(", ").append(j).append("),\n");
        }
        s.append("];\n\n");

        SimplexNoise swamp = new SimplexNoise(new Random(2345L));
        s.append("/// Swamp grass noise at block (x, z): getValue(x * 0.0225, z * 0.0225)\npub const SWAMP: &[(i32, i32, u64)] = &[\n");
        for (int x = -1000; x <= 1000; x += 173) {
            s.append("   ");
            for (int z = -1000; z <= 1000; z += 173) s.append(" (").append(x).append(", ").append(z).append(", ").append(d(swamp.getValue(x * 0.0225, z * 0.0225))).append("),");
            s.append("\n");
        }
        s.append("];\n\n");

        List<double[]> raw = new ArrayList<>();
        Random r = new Random(99);
        for (int i = 0; i < 40; i++) raw.add(new double[]{(r.nextDouble() - 0.5) * 200, (r.nextDouble() - 0.5) * 200});
        double[][] edge = {{0, 0}, {1, 1}, {-1, -1}, {0.5, 0.5}, {1e6, -1e6}, {12345.678, 0.001}, {-0.0, 3}, {2.5e9, 7}, {-300.75, -300.75}};
        raw.addAll(Arrays.asList(edge));
        s.append("/// (x, y, getValue) for the 2345-seeded noise\npub const RAW: &[(u64, u64, u64)] = &[\n");
        for (double[] p : raw) s.append("    (").append(d(p[0])).append(", ").append(d(p[1])).append(", ").append(d(swamp.getValue(p[0], p[1]))).append("),\n");
        s.append("];\n");
        return s.toString();
    }
}
