import java.awt.image.BufferedImage;
import java.awt.image.ColorModel;
import java.awt.image.DataBuffer;
import javax.imageio.ImageTypeSpecifier;
import java.io.ByteArrayOutputStream;
import java.io.DataOutputStream;
import java.nio.file.*;
import java.util.*;
import java.util.zip.CRC32;
import java.util.zip.Deflater;
import javax.imageio.ImageIO;

// Writes a corpus of PNGs (every colour type and bit depth, tRNS variants, all five row filters, Adam7) and what
// ImageIO.read + BufferedImage.getRGB + ImageIO.write (Texture.java's path) make of each.
// args = <bm-resources tests/data dir> <bm-java src/png dir>; writes png/<case>.png, png_ref.txt and gray_lut.rs.
public class PngRef {
    record Case(String name, int width, int height, int colorType, int bits, boolean interlaced,
                int[] samples, byte[] plte, byte[] trns) {}

    static final Random RANDOM = new Random(5051418);

    public static void main(String[] args) throws Exception {
        Path dir = Path.of(args[0]);
        Path pngs = dir.resolve("png");
        Files.createDirectories(pngs);
        StringBuilder ref = new StringBuilder("# @generated by PngRef.java (JDK 25). Do not edit.\n"
                + "# <case> <getRGB of every pixel, 8 hex digits each> <ImageIO.write bytes, hex>\n");
        for (Case c : cases()) {
            byte[] png = encode(c);
            Files.write(pngs.resolve(c.name + ".png"), png);
            BufferedImage image = ImageIO.read(pngs.resolve(c.name + ".png").toFile());
            StringBuilder argb = new StringBuilder();
            for (int y = 0; y < image.getHeight(); y++)
                for (int x = 0; x < image.getWidth(); x++) argb.append(String.format("%08x", image.getRGB(x, y)));
            ByteArrayOutputStream written = new ByteArrayOutputStream();
            ImageIO.write(image, "png", written);
            ref.append(c.name).append(' ').append(argb).append(' ').append(HexFormat.of().formatHex(written.toByteArray()))
                    .append('\n');
        }
        Files.writeString(dir.resolve("png_ref.txt"), ref);
        Files.writeString(Path.of(args[1]).resolve("gray_lut.rs"), grayLuts());
    }

    /** ComponentColorModel's linear-gray → sRGB LUTs (ICC conversion, not a formula), as getRGB applies them. */
    static String grayLuts() {
        ColorModel gray8 = ImageTypeSpecifier.createGrayscale(8, DataBuffer.TYPE_BYTE, false).getColorModel();
        StringBuilder s = new StringBuilder("// @generated by tools/javaref/PngRef.java (JDK 25). Do not edit.\n\n"
                + "/// `getRGB` red/green/blue of an 8-bit linear-gray sample.\npub const GRAY8: [u8; 256] = [");
        for (int v = 0; v < 256; v++) s.append(v % 16 == 0 ? "\n   " : "").append(' ')
                .append(gray8.getRGB(new byte[] {(byte) v}) & 0xff).append(',');
        // the 16-bit LUT is monotonic: store where each output value starts
        ColorModel gray16 = ImageTypeSpecifier.createGrayscale(16, DataBuffer.TYPE_USHORT, false).getColorModel();
        int[] starts = new int[256];
        int last = gray16.getRGB(new short[] {0}) & 0xff;
        if (last != 0) throw new IllegalStateException("gray16(0) = " + last);
        for (int v = 1; v < 65536; v++) {
            int out = gray16.getRGB(new short[] {(short) v}) & 0xff;
            if (out < last) throw new IllegalStateException("gray16 LUT not monotonic at " + v);
            for (int k = last + 1; k <= out; k++) starts[k] = v;
            last = out;
        }
        if (last != 255) throw new IllegalStateException("gray16(65535) = " + last);
        s.append("\n];\n\n/// `GRAY16_STARTS[k]`: the first 16-bit linear-gray sample whose `getRGB` component is `k`.\n"
                + "pub const GRAY16_STARTS: [u16; 256] = [");
        for (int k = 0; k < 256; k++) s.append(k % 16 == 0 ? "\n   " : "").append(' ').append(starts[k]).append(',');
        return s.append("\n];\n").toString();
    }

    static List<Case> cases() {
        List<Case> out = new ArrayList<>();
        for (int bits : new int[] {1, 2, 4, 8, 16}) {
            int max = (1 << bits) - 1;
            // sub-byte rows 13 pixels wide: rows end mid-byte
            int w = bits == 16 ? 32 : bits == 8 ? 16 : 13;
            int[] gray = values(bits == 16 ? 1024 : bits == 8 ? 256 : 39, bits);
            out.add(new Case("gray" + bits, w, gray.length / w, 0, bits, false, gray, null, null));
            // tRNS keys: the top value, and one whose 8-bit scaling differs from the raw sample
            int key = bits == 16 ? gray[100] : bits == 8 ? 77 : max;
            out.add(new Case("gray" + bits + "_trns", w, gray.length / w, 0, bits, false, gray, null, u16(key)));
            if (bits < 8) out.add(new Case("gray" + bits + "_trns_low", w, gray.length / w, 0, bits, false, gray, null, u16(1)));
            if (bits >= 8) {
                int n = 256;
                out.add(new Case("graya" + bits, 16, n / 16, 4, bits, false, values(n * 2, bits), null, null));
                int[] rgb = values(n * 3, bits);
                out.add(new Case("rgb" + bits, 16, n / 16, 2, bits, false, rgb, null, null));
                out.add(new Case("rgb" + bits + "_trns", 16, n / 16, 2, bits, false, rgb, null,
                        concat(u16(rgb[30]), u16(rgb[31]), u16(rgb[32]))));
                out.add(new Case("rgba" + bits, 16, n / 16, 6, bits, false, values(n * 4, bits), null, null));
            }
            if (bits <= 8) {
                int size = 1 << bits;
                for (int entries : bits == 1 ? new int[] {1, 2} : new int[] {size / 2 + 1, size}) {
                    byte[] plte = new byte[entries * 3];
                    RANDOM.nextBytes(plte);
                    int[] idx = new int[w * 4];
                    for (int i = 0; i < idx.length; i++) idx[i] = i % entries;
                    String name = "pal" + bits + "_" + entries;
                    out.add(new Case(name, w, 4, 3, bits, false, idx, plte, null));
                    byte[] trns = new byte[Math.max(1, entries / 2)];
                    RANDOM.nextBytes(trns);
                    trns[0] = 0;
                    out.add(new Case(name + "_trns", w, 4, 3, bits, false, idx, plte, trns));
                }
            }
        }
        out.add(new Case("gray16_adam7", 9, 7, 0, 16, true, values(63, 16), null, null));
        out.add(new Case("rgba8_adam7", 9, 7, 6, 8, true, values(63 * 4, 8), null, null));
        byte[] plte = new byte[12];
        RANDOM.nextBytes(plte);
        int[] idx = new int[63];
        for (int i = 0; i < idx.length; i++) idx[i] = RANDOM.nextInt(4);
        out.add(new Case("pal2_adam7", 9, 7, 3, 2, true, idx, plte, new byte[] {0, (byte) 128}));
        return out;
    }

    /** {@code n} samples: every value for small depths, else the edges then random values. */
    static int[] values(int n, int bits) {
        int max = (1 << bits) - 1;
        int[] edges = {0, 1, 2, 127, 128, 129, 254, 255, 256, 257, 32767, 32768, 32769, 65279, 65280, 65534, 65535};
        int[] v = new int[n];
        int e = 0;
        for (int i = 0; i < n; i++) {
            if (bits <= 8) v[i] = i % (max + 1);
            else if (e < edges.length) v[i] = edges[e++];
            else v[i] = RANDOM.nextInt(max + 1);
        }
        return v;
    }

    static byte[] u16(int v) {
        return new byte[] {(byte) (v >> 8), (byte) v};
    }

    static byte[] concat(byte[]... parts) {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        for (byte[] p : parts) out.writeBytes(p);
        return out.toByteArray();
    }

    static int bands(int colorType) {
        return switch (colorType) {
            case 2 -> 3;
            case 4 -> 2;
            case 6 -> 4;
            default -> 1;
        };
    }

    static byte[] encode(Case c) throws Exception {
        ByteArrayOutputStream raw = new ByteArrayOutputStream();
        int filter = 0;
        if (c.interlaced) {
            int[][] passes = {{0, 0, 8, 8}, {4, 0, 8, 8}, {0, 4, 4, 8}, {2, 0, 4, 4}, {0, 2, 2, 4}, {1, 0, 2, 2}, {0, 1, 1, 2}};
            for (int[] p : passes) {
                List<Integer> xs = new ArrayList<>(), ys = new ArrayList<>();
                for (int x = p[0]; x < c.width; x += p[2]) xs.add(x);
                for (int y = p[1]; y < c.height; y += p[3]) ys.add(y);
                if (xs.isEmpty() || ys.isEmpty()) continue;
                byte[] prev = null;
                for (int y : ys) {
                    byte[] row = packRow(c, y, xs);
                    raw.write(filter);
                    raw.writeBytes(filterRow(filter, row, prev, bpp(c)));
                    prev = row;
                    filter = (filter + 1) % 5;
                }
            }
        } else {
            List<Integer> xs = new ArrayList<>();
            for (int x = 0; x < c.width; x++) xs.add(x);
            byte[] prev = null;
            for (int y = 0; y < c.height; y++) {
                byte[] row = packRow(c, y, xs);
                raw.write(filter);
                raw.writeBytes(filterRow(filter, row, prev, bpp(c)));
                prev = row;
                filter = (filter + 1) % 5;
            }
        }
        Deflater deflater = new Deflater();
        deflater.setInput(raw.toByteArray());
        deflater.finish();
        ByteArrayOutputStream z = new ByteArrayOutputStream();
        byte[] buf = new byte[8192];
        while (!deflater.finished()) z.write(buf, 0, deflater.deflate(buf));

        ByteArrayOutputStream png = new ByteArrayOutputStream();
        png.writeBytes(new byte[] {(byte) 0x89, 'P', 'N', 'G', '\r', '\n', 0x1a, '\n'});
        ByteArrayOutputStream ihdr = new ByteArrayOutputStream();
        DataOutputStream d = new DataOutputStream(ihdr);
        d.writeInt(c.width);
        d.writeInt(c.height);
        d.write(new byte[] {(byte) c.bits, (byte) c.colorType, 0, 0, (byte) (c.interlaced ? 1 : 0)});
        chunk(png, "IHDR", ihdr.toByteArray());
        if (c.plte != null) chunk(png, "PLTE", c.plte);
        if (c.trns != null) chunk(png, "tRNS", c.trns);
        chunk(png, "IDAT", z.toByteArray());
        chunk(png, "IEND", new byte[0]);
        return png.toByteArray();
    }

    static int bpp(Case c) {
        return Math.max(1, bands(c.colorType) * c.bits / 8);
    }

    static byte[] packRow(Case c, int y, List<Integer> xs) {
        int bands = bands(c.colorType);
        int bitsPerRow = xs.size() * bands * c.bits;
        byte[] row = new byte[(bitsPerRow + 7) / 8];
        int bit = 0;
        for (int x : xs) {
            for (int b = 0; b < bands; b++) {
                int v = c.samples[(y * c.width + x) * bands + b];
                if (c.bits == 16) {
                    row[bit / 8] = (byte) (v >> 8);
                    row[bit / 8 + 1] = (byte) v;
                } else if (c.bits == 8) {
                    row[bit / 8] = (byte) v;
                } else {
                    row[bit / 8] |= (byte) (v << (8 - c.bits - bit % 8));
                }
                bit += c.bits;
            }
        }
        return row;
    }

    static byte[] filterRow(int filter, byte[] row, byte[] prev, int bpp) {
        byte[] out = new byte[row.length];
        for (int i = 0; i < row.length; i++) {
            int a = i >= bpp ? row[i - bpp] & 0xff : 0;
            int b = prev != null ? prev[i] & 0xff : 0;
            int cc = prev != null && i >= bpp ? prev[i - bpp] & 0xff : 0;
            int predictor = switch (filter) {
                case 1 -> a;
                case 2 -> b;
                case 3 -> (a + b) / 2;
                case 4 -> paeth(a, b, cc);
                default -> 0;
            };
            out[i] = (byte) (row[i] - predictor);
        }
        return out;
    }

    static int paeth(int a, int b, int c) {
        int p = a + b - c, pa = Math.abs(p - a), pb = Math.abs(p - b), pc = Math.abs(p - c);
        return pa <= pb && pa <= pc ? a : pb <= pc ? b : c;
    }

    static void chunk(ByteArrayOutputStream png, String type, byte[] data) throws Exception {
        DataOutputStream d = new DataOutputStream(png);
        d.writeInt(data.length);
        byte[] t = type.getBytes("US-ASCII");
        d.write(t);
        d.write(data);
        CRC32 crc = new CRC32();
        crc.update(t);
        crc.update(data);
        d.writeInt((int) crc.getValue());
    }
}
