"""Writes THIRD-PARTY-NOTICES.txt (repo root, git-ignored): licenses/BUNDLED.txt, the Quicksand font's OFL text and
the licence texts of every Rust crate in `bluemap`, generated by cargo-about (about.toml, about.hbs).

Usage: py -3 tools/notices.py        (needs `cargo install --locked cargo-about`)
Release builds ship the file in the CLI archives and the jars' META-INF (.github/workflows/release.yml).
"""
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "THIRD-PARTY-NOTICES.txt"


def main() -> None:
    crates = subprocess.run(
        ["cargo", "about", "generate", "--fail", "-m", str(ROOT / "crates/bm-cli/Cargo.toml"), str(ROOT / "about.hbs")],
        cwd=ROOT, check=True, capture_output=True, text=True, encoding="utf-8").stdout
    ofl = (ROOT / "crates/bm-web/webapp/assets/OFL.txt").read_text(encoding="utf-8").replace("\r\n", "\n")
    bundled = (ROOT / "licenses/BUNDLED.txt").read_text(encoding="utf-8")
    OUT.write_text(f"{bundled}\n\n== SIL Open Font License 1.1 (Quicksand) ==\n\n{ofl}\n\n{crates}", encoding="utf-8",
                   newline="\n")
    print(f"{OUT.name}: {OUT.stat().st_size / 1024:.0f} KiB")


if __name__ == "__main__":
    main()
