[package]
name = "bm-map"
edition.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true
description = "BlueMap map-level state: render state (rstate)"

[dependencies]
bm-compress.workspace = true
bm-format.workspace = true
bm-nbt.workspace = true
thiserror.workspace = true
